### ISSUE TITLE
An unhandled error has occurred. Reload

### ISSUE THREAD

**Issue by ToddTSU** [kswoll/xohoops#14]
When clicking on the tabs for NBA player stats, e.g. [https://xohoops.net/nba/stats/players/fouls](https://xohoops.net/nba/stats/players/fouls) , the page gives the error message that "An unhandled error has occurred. Reload."  When I reload, it works fine until I change tabs again.

**Comment by kswoll** [comment]
Hey Todd, I just tested now and it worked fine.  I've made a few changes to that page in the last day, so possibly it got incidentally fixed.  Can you try again and let me know if it's still happening?

**Comment by ToddTSU** [comment]
Just tested and it appears to be fixed!  I can navigate between tabs with no errors.

**Comment by kswoll** [comment]
Awesome, thanks for confirming!
