### ISSUE TITLE
Creating new message on mobile

### ISSUE THREAD

**Issue by devin-b** [kswoll/xohoops#4]
Cannot create a new message when on a mobile device.  Typing in name in the "to" section does nothing.  

Only solution is to find and old message between you and that person and respond to it.

**Comment by kswoll** [comment]
@devin-b I can't repro on iOS/Chrome.  Can you let me know what OS and browser you are using?

**Comment by devin-b** [comment]
Chrome on Android Nexus 5X.

**Comment by kswoll** [comment]
Was able to repro on my old Android phone and confirmed fixed on that phone.  Let me know if you still have any troubles.

**Comment by devin-b** [comment]
Works now.  Thanks!
